### ISSUE TITLE
Practica_3_Mapas_de_K

### ISSUE THREAD

**Issue by Fidel20-01** [SistemasTecTlaxiaco/actividad-12-ejercicios-de-mapas-de-karnaught-equipo-de-jp#2]
[Act3_Reporte_Practica_Spring4_Mate_D.pdf](https://github.com/user-attachments/files/18044533/Act3_Reporte_Practica_Spring4_Mate_D.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 20
